### ISSUE TITLE
[BUG] axis assignment

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#104]
auto ba{ kwk::height[ 3 ] };
ba = 2;

error : use of overloaded operator '=' is ambiguous (with operand types 'axis_<rbr::literals::str{"height", 7}, decltype(v)>' (aka 'axis_<rbr::literals::str{"height", 7}, int>') and 'int')
kiwaku\include\kwk\detail\raberu.hpp(397,20): message : candidate function [with Type = int]
kiwaku\include\kwk\settings\axis.hpp(24,10): message : candidate function (the implicit move assignment operator)
kiwaku\include\kwk\settings\axis.hpp(24,10): message : candidate function (the implicit copy assignment operator)

**Comment by jfalcou** [comment]
yeah the error message is not great but what do you want this to do ?
height[3] is suppsoed to be a static size not a dynamic one so I am confused to what you want to achieve

**Comment by jfalcou** [comment]
`auto ba = (kwk::height = 3);`

shoudl work though.

**Comment by psiha** [comment]
oops 😊
