### ISSUE TITLE
sizeof static shape

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#20]
Currently a fully static shape is not an empty class (and I rely on this being the case for cross-compilation ABI reasons) - its size is not zero when used with EBO - this is due to the storage_ data member.
For some compilers this should/could be fixed by simply slapping [[ no_unique_address ]] on the member however this does not help with, you guessed it, MSVC or even Clang-CL - for that usual pain in the behind you have to derive from the storage_ type _and_ slap __declspec( empty_bases ) on the shape struct to be sure that EBO will kick in (yes 🙄)

**Comment by jfalcou** [comment]
This was on my short list cause it once trounced me. Will investigate.

**Comment by jfalcou** [comment]
OK, making shape inheriting from the storage fixes the issue for g++/clang.
On MSVC, this test

```c++
struct other_base { int x; };

struct ebo_carrier : kwk::shape<kwk::extent[42][69]>, other_base {};

TTS_CASE( "kwk::shape and Empty Base Optimisation" )
{
  TTS_CONSTEXPR_EQUAL( sizeof(ebo_carrier), sizeof(other_base) );
};
```

does not fail **without __declspec(empty_bases)**.
Is it normal or should I make the test more complex?

Branch fix-20/shape_proper_empty_base contains the changes if you want to try locally.

Also why not using [[msvc::no_unique_address]] instead of the ugly old declspec ?

**Comment by psiha** [comment]
>Is it normal or should I make the test more complex?

well i would expect it to work actually - according to the documentation for empty_bases, it is a workaround for (broken ms abi) issues with _multiple_ inheritance - i just got used to slapping it on whenever i really need ebo - easier than getting bitten later by dubious runtime errors...
although having a test to verify just that should serve the same purpose equally 👍 

> Also why not using [[msvc::no_unique_address]] instead of the ugly old declspec ?

did not try it in this case - but in other similar cases it did not help (i suspect it is yet another dumb ms abi backward compatibility thing - as it did not work as expected with clang-cl either)...

**Comment by jfalcou** [comment]
Ok, I will try to add a bunch more complex cases to the test.

**Comment by jfalcou** [comment]
Added more tests. Feel free to comment on them and if it's OK this way (without the declspec), I will merge
