### ISSUE TITLE
nbdims&co return/value type

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#21]
Is it really necessary/reasonable to use signed 64bit type for the number of dimensions?
8bits should pro'lly be enough for 99% of everybody 😁 or at least go with uint32 - to avoid using 64bit instructions...
(the required type could in fact be inferred from the number of static_order but for starters i'd be pleased with at least dropping down to 32bits)

**Comment by jfalcou** [comment]
Yeah I saw that. I think it should return auto and let int promotion kicks in. Returning size_type may leader to bad surprise with small integers.
