### ISSUE TITLE
Complete support for kwk::table

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#25]
Where have the sources for the owning container/array.hpp gone? 🤔 

---

Remaining tasks:
 - [x] table basic tests
 - [ ] move/copy tests

**Comment by jfalcou** [comment]
And we go down soon with the current PR

**Comment by jfalcou** [comment]
The old code was a mess

**Comment by psiha** [comment]
🙈  ok waiting impatiently 😁

**Comment by jfalcou** [comment]
Fixed by #50
