### ISSUE TITLE
Easier shape construction

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#26]
Construction syntax for partially static shapes is IMO really cumbersome - the axis placeholder syntax is _cool_ and useful certainly for some situations, in others (most ones in our use cases) however it would be easier if we could have the 'old school less cool eigen' syntax ;D +i'd expect this syntax to be faster to compile ;D
i.e. so that one can simply pass values to the constructor using plain C syntax - and the library will simply assert that the values passed for fixed/static axis match the static values...
A companion version that takes only as many arguments as there are dynamic dimensions (and assigns them in order) would also be useful...

**Comment by jfalcou** [comment]
```
i.e. so that one can simply pass values to the constructor using plain C syntax - and the library will simply assert that the values passed for fixed/static axis match the static values...
```

I am not a fan of that.

**Comment by psiha** [comment]
> I thought we agreed already it need to change? I don't like the axis ctor after all.

Don't remember that discussion...
I like the axis syntax - as nerd porn for rubbing it in back to the Python ML engineers 😁 
...just that in 'real life' it requires serious/verbose gimnastics (which also certainly aren't CT cheap)...
 
> The accept the exact # of dynamic size should be trivial.

👍 

> What is the eigen way ?

the thing you aren't a fan of 😁

**Comment by jfalcou** [comment]
axis is just a funky object that do some stati_assert in a ... so not costly.
I'll made amendment for the shape{int...} constructor to take static_size in consideration it will already helps

**Comment by psiha** [comment]
> axis is just a funky object that do some stati_assert in a ... so not costly.

The cost is not in the axis object itself but in what it requires 'around' itself (e.g. case in point is exactly the of_shape implementation)

**Comment by jfalcou** [comment]
OK, what if we do it the other way around?

```c++
shape<extent()[4]()> x(3, _, 7);
```

**Comment by jfalcou** [comment]
Still has the issue of trying to construct the type in a generic context :/

**Comment by psiha** [comment]
> OK, what if we do it the other way around?
> 
> ```c++
> shape<extent()[4]()> x(3, _, 7);
> ```

this is cool too :)

i'd like the version where you could also simply write 3, 4 ,7...but i can first try with this...

**Comment by jfalcou** [comment]
I have to convince myself the full blown own is easier.
Maybe we can make it so if you pass a value, it is checked against the static ones and _ is a joker of some sort
Thus it'll fit both use cases

**Comment by psiha** [comment]
nice 👍

**Comment by jfalcou** [comment]
https://github.com/jfalcou/kiwaku/pull/36

**Comment by jfalcou** [comment]
Merged
