### ISSUE TITLE
linear_index does colmajor/inverse axis order?

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#39]
1. I have a `kwk::shape< 1, 0, 0 > my_shape{ 1, 4, 4 }` i.e. a shape with the first/major/leftmost dimension fixed at 1 and the other two dynamically set to 4.
2. I then try to iterate over the shape (effectively a matrix) using `kwk::linear_index( my_shape, 0, h, w )` but it keeps returning index values as if h w are swapped (i.e. as if it is returning col-major linearized indices)

```
kwk::shape<{{{1, 0, 0}}}>
  std::__2::array<unsigned short,2>	{__elems_=0x000000e8910fdb20 {4, 4} }
	__elems_	0x000000e8910fdb20 {4, 4}	unsigned short[2]
        [0]	4	unsigned short
        [1]	4	unsigned short
```

this is what i have in the debugger in linear_index.hpp line 29
```
 template<auto Shaper, std::integral... Index>
  auto linear_index( shape<Shaper> const& sh, Index... idx )
  {
    return sh.as_stride().index(idx...);
  }
```
```
kwk::detail::linearize<kwk::stride<{}>,0,1,2,int,unsigned short,unsigned short> returned	1	int
this	0x000000e8910fd8c0 {storage_={__elems_=0x000000e8910fd8c0 {1, 4, 583} } }	const kwk::stride<{}> *
is	0	int
is	1	unsigned short
is	0	unsigned short
```

IOW: linearize returned 1 instead of 4 - and when I pass 0 0 1 then it returns 4 instead of 1...
...plus there is this weird big/garbage value (583) which changes with each restart/recompile...

**Comment by jfalcou** [comment]
Guess I fumbled something when computing hybrid shape's stride. I'll add a test and fix that tomorrow

**Comment by jfalcou** [comment]
Ok back to that:

Code:
```c++
#include <iostream>
#include <kwk/container/linear_index.hpp>

int main()
{
  auto s = kwk::shape<kwk::extent[1]()()>{kwk::_,4,4};
  std::cout << s << "\n";
  std::cout << s.as_stride() << "\n";

  for(int w=0;w<4;w++)
    for(int h=0;h<4;h++)
      std::cout << "0 " << h << " " << w << " = " << kwk::linear_index( s, 0, h, w ) << "\n";
}
```

Output :

```c++
[ 1 4 4 ]
[{ 1 1 4 }]
0 0 0 = 0
0 1 0 = 1
0 2 0 = 2
0 3 0 = 3
0 0 1 = 4
0 1 1 = 5
0 2 1 = 6
0 3 1 = 7
0 0 2 = 8
0 1 2 = 9
0 2 2 = 10
0 3 2 = 11
0 0 3 = 12
0 1 3 = 13
0 2 3 = 14
0 3 3 = 15
```

So for me, it looks OK. Can you show me your exact code ?

**Comment by psiha** [comment]
so you cannot reproduce it after all?

**Comment by psiha** [comment]
> So for me, it looks OK. Can you show me your exact code ?

@jfalcou actually it does not look (to me)::
- you've reversed the for loops - iterating first/inner over h and then/outer over w
- strides for (row major) [1 4 4] are [ 16 4 1 ] not [ 1 1 4 ]...??

...this is now actually a showstopper for me :/

**Comment by psiha** [comment]
one dimension being static actually makes no difference - even with the first/unit dimension being dynamic i get the same results...

also if for shape{ 4, 4, 4 } i get stride{ 1, 4, 16 } - so it is definitely reversed ('col major')..

**Comment by jfalcou** [comment]
Wait, you're confusing a lot of things.
 - There is no row/col in Kiwaku, just inner->outer dimensions, you call them w/e.
 - The stride computation follow the inner->outer order and always have been
 - That's why the loop are the way i wrote them, you iterate from outer to inner indexes

So you're operating under the false hypothesis we made an orientation choice. But we didnt. 
Row and cols are confusing (see), only the physical order is important

If you want to run over data with a stride of [4 1 4] ( [16 4 1] is never a thing as the 3rd dimension play no role, see how FORTRAN do it), you will need the storage_order option (see #8).

**Comment by psiha** [comment]
I used the row-col major nomenclature simply because it is the simplest, most oft used to discuss this issue of physical vs logical addressing/layout. But, yes C vs Fortran is a better/more general distinction: so the way I see it is that you/kiwaku uses/assumes Fortran physical layout for calculating the strides?

So let's try it this way:
have 3D shape, [x, y, z]
with: x = 1, y = 2, z = 3
auto s = kwk::shape<kwk::extent()()()>{1,2,3};
std::cout << s.as_stride() << "\n";
then for C layout we should get { 6, 3,1 }
while kiwaku calculates and outputs the Fortran layout strides { 1, 1, 2 }
?

Is this (Fortran layout assumptions) intended and if so why? ;P
Also can I somehow switch it to C logic or must I write my own stride functionality?

**Comment by psiha** [comment]
> If you want to run over data with a stride of [4 1 4] ( [16 4 1] is never a thing as the 3rd dimension play no role

I know/realize that one (first or last, depending on C vs Fortran) stride element 'plays no role' as in it is always 1 (if that is what you meant)?

...but I don't know what these numbers "[4 1 4] ( [16 4 1]" represent in this example you gave...

**Comment by psiha** [comment]
ps. linear_index() does not sanitize its inputs - i.e. out-of-range values get accepted (and outputs nonsense)

**Comment by psiha** [comment]
I tried manually reversing the dimensions to get the expected strides but then I got the expected strides value-wise but again in reversed order ( [1, 3, 6] instead of [6, 3, 1])

```
`using Dims = kwk::shape<kwk::extent()()()>;
    Dims s{1,2,3};
    std::cout << s << "\n";
    std::cout << s.as_stride() << "\n";

    for (int h = 0; h < 2; h++)
        for(int w=0;w<3;w++)
            std::cout << "0 " << h << " " << w << " = " << kwk::linear_index( s, 0, h, w ) << "\n";

    auto sr = [ & ]< std::uint8_t... i >( std::integer_sequence< std::uint8_t, i... > )
    {
        using Reversed = Dims;
        Reversed const reversed{ s.get< s.static_order - i - 1 >()... };
        return reversed;
    }( std::make_integer_sequence< std::uint8_t, s.static_order >{} );
    std::cout << sr << "\n";
    std::cout << sr.as_stride() << "\n";
    for (int h = 0; h < 2; h++)
        for (int w = 0; w < 3; w++)
            std::cout << "0 " << h << " " << w << " = " << kwk::linear_index( sr, 0, h, w ) << "\n";`
```

output:

```
[ 1 2 3 ]
[{ 1 1 2 }]
0 0 0 = 0
0 0 1 = 2
0 0 2 = 4
0 1 0 = 1
0 1 1 = 3
0 1 2 = 5
[ 3 2 1 ]
[{ 1 3 6 }]
0 0 0 = 0
0 0 1 = 6
0 0 2 = 12
0 1 0 = 3
0 1 1 = 9
0 1 2 = 15
```

**Comment by jfalcou** [comment]
The basic premise of shape and access in Kiwaku is that if your shape is [d0 d1 d2], your expected to walk over your data with loop over d2 then d1 then d0 as the inner most loop, and passing d0 d1 d2 as parameters.
Storage order options will later let you disconnect logical from physical order, thus requiring you to use a loop algorithm to ensure you alk over the data in the proper way.

What you're doign here is just not what we await

**Comment by psiha** [comment]
..lemme finally get back to this :)

so, first i must say i was quite 'confunded' (to put it mildly) that your default 'behaviour' is exactly the opposite of the 'usual' approach, the C layout and the interface/axis order that other libraries use (even if they use the 'fortran' layout underneath) (e.g. Eigen is by default col-major internaly yet you still specify/index dimensions like ( h, w ), not ( w, h ) ... + that it is fixed/unchangeable ... (which most probably would be a show stopper for us)

...yet from the slew of changes/pr's lately it seems you have changed your mind? :)

**Comment by jfalcou** [comment]
Yeah we're looking at solving this properly and reinstate C based default afterward.

**Comment by jfalcou** [comment]
For the parameter order, my idea was that the index i0...in should be in the same order as the size construction d0...dn
Their **interpretation** in the physical memory land can be changed. SOme stuff is gonna dropa t some point to clarify that.

**Comment by jfalcou** [comment]
Sorry I am lost again.

See:
https://godbolt.org/z/G7PWb8s61

I don't get what we are reversing. If you put the size is the "kiwaku" order, it just works(tm) as th eloop is the same as the C style one.
