### ISSUE TITLE
Questions about this?

### ISSUE THREAD

**Issue by LedLoaf** [jfalcou/kiwaku#4]
Hello,

I'm not finding any more information on here about this project? I was curious of what this project is and what makes it better than say the std:: containers? If you can just give me some more information, I'd appreciate it and you can just remove this post after. I found the description of this library from Compiler-Explorer.

**Comment by jfalcou** [comment]
Hi,
kiwaku's goal is to provide flexible and efficient N-Dimensions containers for numerical computations along with views and a bunch of N-D algorithms.

A bunch of work is currently being done and needs to be pushed over here.
