### ISSUE TITLE
stride uses size_type from shape

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#41]
When using shorts for shapes that is a problem - 16bits is easily overflowed (for our use cases we'd need uint32_t for strides - although strictly the first/rightmost one is fix one, the next is copied short and only the third and further ones need 32bits)...

**Comment by jfalcou** [comment]
Oh that's indeed an oversight. Won't it make the win on size from the shape not ported over stride , thus leading to larger objects ?

**Comment by jfalcou** [comment]
Fixed when #50 is merged

**Comment by psiha** [comment]
> Won't it make the win on size from the shape not ported over stride , thus leading to larger objects ?

In some cases it will/it might - however I was under the impression that strides are temporary or at most local objects (and passed around inlined code)...not actually (usually) stored anywhere (long term, like the heap)?

**Comment by jfalcou** [comment]
In fact, it'll be solved as, in the current PR, shape AND stride share the same mixed CT/RT size storage so, should be good.

**Comment by jfalcou** [comment]
This needs a specific unit test now that #50 is merged so we can act accordingly
