### ISSUE TITLE
BOOST_ASSERT as KIWAKU_ASSERT no longer works

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#83]
Now that you have started using iostream constructs in invocations of KIWAKU_ASSERT this fails to compile when BOOST_ASSERT is used
https://user-images.githubusercontent.com/340735/222702614-350a6e2f-67aa-438f-97a5-dc62f82c2084.png

The first fix is to remove BOOST_ASSERT support and let/us other provide our own KIWAKU_ASSERT implementation. The core issue for us is the use of iostreams (yuck :D) and also a different 'abort' point (more then one place to place a break point and/or stacktrace printouts for CI environments).

**Comment by jfalcou** [comment]
For ergonomics purpsoe, we need rich assert message that carries the runtime values that may have failed, hence the changes.
We can easily replicate the BOOST_ASSERT_HANDLER protocol for KIWAKU_ASSERT no problem.

**Comment by jfalcou** [comment]
OK, plan can be:
 - make ASSERT takes the string of << infos into a tuple
 - pass the tuple to a assert_handler that do either stream stuff or w/e you want when overridden
 
 This way we keep the rich info where we want and if you need a degraded support of assert, you can safely ignore them and not need any ostream thing.

**Comment by psiha** [comment]
took a stab at this - can you please take a look at https://github.com/jfalcou/kiwaku/actions/runs/4373496578/jobs/7651745697 ?
is this some unhappy kiwaku<->std::tuple interop issue?

**Comment by jfalcou** [comment]
Yes. THink you need ot use kumi::tuple.

**Comment by jfalcou** [comment]
Fix merged
