### ISSUE TITLE
#if _MSC_VER

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#86]
Clang-CL also defines _MSC_VER - so consider using something like if ( defined(_MSC_VER) && !defined(__clang__) ) for stuff really msvc specific (what BOOST_MSVC is for).

ps. saw this when reviewing the KWK_CONST change - so two 'btw' points here:
 - member (non static) functions can at most be pure (because of the this pointer)
 - MSVC has something very similar __declspec( noalias )

**Comment by jfalcou** [comment]
Oh true, I forgot about that. we may need to setup a clang-cl CI bot too.

**Comment by psiha** [comment]
https://github.com/jfalcou/kiwaku/issues/87 fixes this for the code i've seen

**Comment by jfalcou** [comment]
Fixed in b1c24398e7755649a314283c29b7e7dbe9ff799e
