### ISSUE TITLE
[FEATURE] Policy for default dynamic axis values

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#97]
(in shape default construction): your current logic/behaviour:
//! @brief Constructs a default @ref kwk::shape equals to [1 1 ... 0]
does not 'work' for me - in my wrapper I have to override it by resetting everything to zero.

I know this is another oh crap facepalm moment but 🤷 :/

**Comment by jfalcou** [comment]
Well, this is an old thign I ported from NT2.
We can live with default shape beign all 0.
Feel free to PR it and change the tests, this is not a hill I'll die on.

**Comment by psiha** [comment]
ok, next how about the policy for constructing a shape with less dimension values then the number of axes?
currently it fills the shape object _left -> to right_ - so `kwk::shape< kwk::extent()()()() > bla( 3, 5, 2 );`  makes bla == [3, 5, 2, 0] - is this really desired/needed anywhere?
imo it is more intuitive that shape gets filled right/minor to left/major and the missing ones get set to 1 - so the above example would be bla == [1, 3, 5, 2] ... ?

**Comment by jfalcou** [comment]
That is a bug from the before C order time. It should be as you describe

**Comment by psiha** [comment]
> That is a bug from the before C order time. It should be as you describe

what does the ( !std::is_convertible_v<S,value_type> ) branch do/what is it for?
(the `if constexpr(contains(i)) v[location[i]] = (i != static_size-1);` line?)

**Comment by psiha** [comment]
done in https://github.com/jfalcou/kiwaku/pull/98
