### ISSUE TITLE
[FEATURE] Shape type construction from a dimensions variadic pack

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#99]
without the need for the dectlype( kwk::of_sze( dims... ) ) 'hack'

**Comment by psiha** [comment]
e.g. `kwk::shape< 4, kwk::height, kwk::width[ 3 ], short{ 8 } >`
asterisk/mul approach:
`kwk::shape< 4 * kwk::height * kwk::width[ 3 ] * short{ 8 } >`
does not work either

**Comment by jfalcou** [comment]
It never meant to. That is not the interface we decided on.
I will think about a proper one.

**Comment by psiha** [comment]
in the mean time, how can i do the above at all (even with decltype) - i.e. combine 'named axes' (e.g. kwk::height) and plain integral extents to define a shape type?

**Comment by jfalcou** [comment]
I am thinking about it.

**Comment by jfalcou** [comment]
would we be satisfied with a 

```c++
using my_shape_t = kwk::make_shape_t<Values...>;
```

that internally do the of_size hack ?
of_size type computation is takign care of everythign the way we want so maybe just wrapping it up is a solution ?

My main issue with `shape<4 * height * 8>` is that someone will write `shape<4 * 8>` and be sad

**Comment by jfalcou** [comment]
Alternative:

```c++
shape< extents(4, height, width[3], 8)> s;
```

note the extent**S** instead of extent as usual.

WDYT ?

**Comment by jfalcou** [comment]
OK after some fiddling, the extents solution (ie ditching the ()[] bonanza) actually leads to multiple things:
 - code looks simpler
 - it solves the hetero shape and other related issues
 - supports ... natively

SO I'll try to go down this path and see how far it goes.

**Comment by psiha** [comment]
> OK after some fiddling, the extents solution (ie ditching the ()[] bonanza) actually leads to multiple things:
> 
> * code looks simpler
> * it solves the hetero shape and other related issues
> * supports ... natively
> 
> SO I'll try to go down this path and see how far it goes.

👍 co_await... 🍇 😁

**Comment by psiha** [comment]
to be sure 'the bonanza' iz cool and also useful in some places...but yes i'd suppose that it is easier and more efficient to first implement the 'standard' ... api and the bonanza on top of it

**Comment by jfalcou** [comment]
the bonanza has the issue that he makes the API full of redundant way of doing thing. Not sure it'll come back this way.
I'll see.

**Comment by jfalcou** [comment]
One example is that with the new system `extents(4,4)` is indeed a 4x4 static extents. In the old one, you have to use `[4][4]` and if by mistake you do `along<1> = 4, along<0> = 4`, it's dynamic caause it's 4 and not `4_c`.

**Comment by psiha** [comment]
> Alternative:
> 
> ```c++
> shape< extents(4, height, width[3], 8)> s;
> ```
> 
> note the extent**S** instead of extent as usual. Of course, we provide a extents_of too. WDYT ?

do you really need the intermediate descriptor thingy (produced by extents) here (i guess shape does not use those rbr options and other such things)? i.e. what do you gain with shape< extents(...) > over just shape< ... >

**Comment by jfalcou** [comment]
It helps because the NTTP contains a lot of precomputed info that lessen the compile time on shape.
I am trying to make it as slim as possible in the rewrite.

**Comment by psiha** [comment]
> It helps because the NTTP contains a lot of precomputed info that lessen the compile time on shape. I am trying to make it as slim as possible in the rewrite.

it makes a difference on the compile time whether this info is computed in an intermediate type instead of in shape itself?

**Comment by psiha** [comment]
eta? 😬 😊

**Comment by jfalcou** [comment]
I will try to get a polishzd thing for the upcoming week. Been busy with training .
